export const THEME = {
  basicFont: 'NanumMyeongjo',
  buttonFont: 'NanumMyeongjo',
  plainFont: 'NanumSquareR',
  titleFont: 'Kim_Gu',
  backgroundColor: '#030A26',
  quest_backgroundColor: '#334D70',
  modal_backgroundColor: '#ffffff',
  quest_boxColor: '#0E305B',
  textColor: '#6D4F3E',
  quest_textColor: '#F1EEE9',
  buttonColor: '#6D4F3E',
  buttonPressColor: '#33231A',
  lightBeige:'#E3DBCE',
}
